### ISSUE TITLE
How to generate training files for yolo?

### ISSUE THREAD

**Issue by syuie** [blaccerik/tft#7]
Thanks for your nice work.

I tried using trained network to detect and recognize champions and items but not too satisfied with accuracy, so I want to reproduce the process of training model weights and try to train YOLOv5 network but no sure how to generate training data, could you provide training data or some tips for how to generate it?

**Comment by blaccerik** [comment]
As I understand yolos:
   | speed (fps) | accuracy | training time
1 | yolov4        | yolov4    | yolov5
2 | yolov5        | yolov5    | yolov3
3 | yolov3        | yolov3    | yolov4

So in your case, if you want accuracy I would recommend using yolov4 but since I used google colab for training and they have limits on training time and hardware then I don't think v4 would train in that time so v5 would be the best bet.

As for data I just went into normal games and took pictures of every alive player and labeled them myself using labelimg
Here's all my images and their labels:
https://drive.google.com/file/d/1AWohSsXno-kbaMBPZzRjDZZ8gpHJAMZ1/view?usp=sharing

good luck

**Comment by syuie** [comment]
Thanks for your kindly help, it helps a lot:)
